import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import Header from "@/blocks/Header/Header";
import Footer from "@/blocks/Footer/Footer";
import About from "@/blocks/About/About";
import Banner from "@/blocks/Banner/Banner";
import BannerSecond from "@/blocks/BannerSecond/BannerSecond";
import HomeCards from "@/blocks/HomeCards/HomeCards";
import BannerThree from "@/blocks/BannerThree/BannerThree";
import ProductGridItem from "@/blocks/ProductGridItem/ProductGridItem";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header/>     
        <Banner/> 
        <BannerSecond/>
        <HomeCards/>
        <BannerThree/>
        <ProductGridItem/>
        <About/>
        <Footer/>
      </div>
    </>
  );
}
